# -*- coding: utf-8 -*-
"""init db

Revision ID: 62429be9b93e
Revises:
Create Date: 2024-06-22 10:13:46.572607

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa
import src
import src.core
import src.core.database


# revision identifiers, used by Alembic.
revision: str = '62429be9b93e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'users',
		sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
		sa.Column('name', sa.String(), nullable=True),
		sa.Column(
			'password', src.core.database.postgresql.addons.password.PasswordType(), nullable=True
		),
		sa.Column(
			'date_of_birth',
			src.core.database.postgresql.addons.datetime.DatetimeType(),
			nullable=True,
		),
		sa.PrimaryKeyConstraint('id'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('users')
	# ### end Alembic commands ###
